os: osx
osx_image: xcode8.2
language: node_js
node_js:
    - "7.7.3"
addons:
  firefox: "45.0"
before_install:
 - export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-45.0&lang=en-US&os=osx'
before_script:
  - cd lib/jsorolla
  - npm install
  - cd ../..
  - npm install
script:
  - grunt
notifications:
  email:
    recipients:
      - jagi.work@gmail.com
    on_success: always
    on_failure: always
