os: linux

dist: trusty

sudo: false

language: node_js

node_js:
    - "7.8.0"

addons:
  firefox: "45.0"

before_install:
 - firefox --version
# to set the screen resolution
 - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1800x1024x16

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - cd lib/jsorolla
  - npm install
  - cd ../..
  - npm install

script:
  - grunt --env=staging

notifications:
  email:
    recipients:
      - jagi.work@gmail.com
    on_success: always
    on_failure: always