os: linux

dist: xenial

services:
  - xvfb

sudo: false

language: node_js

node_js:
    - "7.8.0"

addons:
  firefox: "66.0"

before_install:
 - firefox --version

before_script:
  - cd lib/jsorolla
  - npm install
  - cd ../..
  - npm install

script:
  - grunt --env=staging

notifications:
  email:
    recipients:
      - jagi.work@gmail.com
    on_success: always
    on_failure: always
