os: linux

dist: xenial

services:
  - xvfb

sudo: false

language: node_js

node_js:
    - "10.19.0"

addons:
  chrome: stable

before_script:
  - cd lib/jsorolla
  - npm install
  - cd ../..
  - npm install

script:
  - grunt --env=staging

notifications:
  email:
    recipients:
      - jagi.work@gmail.com
    on_success: always
    on_failure: always
