dist: trusty
sudo: false
language: node_js
node_js:
    - "7.7.3"
addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable
before_script:
  - cd lib/jsorolla
  - npm install
  - cd ../..
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
script:
  - grunt
notifications:
  email:
    recipients:
      - jagi.work@gmail.com
    on_success: always
    on_failure: always



